-- ============================================================================
-- Golden Voice participation videos — private Storage bucket
--
-- Videos are never public. Uploads happen only through short-lived signed
-- upload URLs generated by the serverless endpoint with the service role, and
-- reads use signed URLs in a future admin interface.
-- ============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'golden-voice-videos',
  'golden-voice-videos',
  false,
  209715200, -- 200 MB, mirrors GOLDEN_VOICE_MAX_VIDEO_BYTES / VIDEO_MAX_BYTES
  array['video/mp4', 'video/webm']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ----------------------------------------------------------------------------
-- Storage access policies
--
-- `storage.objects` has RLS enabled by Supabase. This migration intentionally
-- creates NO policy for `anon` or `authenticated`, so public visitors cannot
-- list, read, update, or delete objects in this bucket. The service role used
-- by the serverless endpoints bypasses RLS.
--
-- Do NOT add a public SELECT policy or an anonymous write policy for this
-- bucket. If a future admin UI needs to read videos, issue short-lived signed
-- URLs from an authenticated, role-checked server endpoint instead.
-- ----------------------------------------------------------------------------
